- name: conditional for template 
  hosts: all 
  gather_facts: false 
  tasks:
  - name: copy the file 
    template:
     src: kumar.j2
     dest: /home/ansible/jack.txt
--- 
- name: conditional for template 
  hosts: web 
  gather_facts: false
  vars:
   x: 10
   y: 25
   p: [3,5,6,7,8]
  tasks:
  - name: copy the file with conditional 
    template:
      src: kumar.j2
      dest: /home/ansible/jack.txt
#Note: Need to create the file
--- 



