- name: logical operatores 
  hosts: all
  vars:
   x: 2
   y: 10
   p: [1,3,5,8]
  tasks:
  - name: logical operations
    debug:
     msg:
      - "the value of x is {{x}} and value of y is {{y}}"
      - "the x < y and y in p {{ x < y and x in p }}"
      - "{{ (4>2) and (2<1) and (10>20) }}"
      - "{{ (4>2) or (2<1) or (10<20) }}"
      - "{{ not (4>1) }}"
   # and , or most it is used to club multiple results
   # and output is true only all as true other it false
   # or if any one is true , the output is true
   # if want to change true as false we can use not
